media:
  - name: hero-images
    label: Images de couverture
    input: src/assets/images
    output: /assets/images
    categories: [image]

  - name: event-images
    label: Images de la section Agenda
    input: src/content/event/images
    output: /content/event/images
    categories: [image]

  - name: restaurant-images
    label: Images de la section Restaurant
    input: src/content/restaurant/images
    output: /content/restaurant/images
    categories: [image]

  - name: nearby-images
    label: Images de la section À Proximité
    input: src/content/nearby/images
    output: /content/nearby/images
    categories: [image]

  - name: docs-menus
    label: PDF des menus et cartes
    input: public/docs/menus
    output: /docs/menus
    categories: [document]

content:
  # General Site Information & Settings
  - name: site
    label: "Informations"
    type: file
    path: src/content/site/settings.md
    fields:
      - name: site_title
        label: "Titre du site"
        type: string
        default: "Chez Nous"
      - name: site_description
        label: "méta-descriptions des pages"
        type: object
        fields:
          - {
              name: accueil,
              label: "méta-descriptions de la page d'accueil",
              type: string,
              default: "Chez Nous, pizzeria artisanale à Vermenton (89270). Dégustez des pizzas faites maison, sur place, dans une ambiance conviviale avec des ingrédients frais et de qualité.",
            }
          - {
              name: mentions_legales,
              label: "méta-descriptions de la page des mentions légales",
              type: string,
              default: "Consultez les mentions légales du site Chez Nous (Vermenton, 89270). Retrouvez les informations sur la propriété, l'hébergement, la responsabilité et les conditions d'utilisation de notre site web artisanale.",
            }
          - {
              name: politique_de_confidentialité,
              label: "méta-descriptions de la page de politique de confidentialité",
              type: string,
              default: "Découvrez la politique de confidentialité de Chez Nous. Informez-vous sur la manière dont nous collectons, utilisons et protégeons vos données personnelles lorsque vous naviguez sur notre site de pizzeria à Vermenton.",
            }

      - name: hero_title
        label: "Sous-titre du site"
        type: string
        default: >
          Pizza,
          Pasta,
          Dolce vita
      - name: socials
        label: "Liens des réseaux sociaux"
        type: object
        fields:
          - {
              name: instagram,
              label: Instagram,
              type: string,
              default: "https://www.instagram.com/cheznous89270/",
            }
          - {
              name: facebook,
              label: Facebook,
              type: string,
              default: "https://www.facebook.com/cheznous89270/",
            }
      - name: contact
        label: "Information de contact"
        type: object
        fields:
          - {
              name: address,
              label: Adresse,
              type: string,
              default: "7 place de la Convention – 89270 Vermenton",
            }
          - {
              name: phone,
              label: "Téléphone (affiché)",
              type: string,
              default: "03 86 51 89 56",
            }
          - {
              name: phone_link,
              label: "Téléphone (lien cliquable)",
              type: string,
              default: "+33686518956",
            }
          - {
              name: email,
              label: Adresse email,
              type: string,
              default: "contact@cheznous89270.com",
            }
      - name: opening_hours
        label: "Horaires d'ouverture"
        type: string
        default: "Ouvert du mardi au samedi de 11h30 à 14h30 et de 18h30 à 21h. Le dimanche, uniquement le midi de 11h30 à 14h30."
      - name: slogan
        label: "Slogan du site"
        type: string
        default: "Pizzas artisanales préparées à la maison"

  - name: closure
    label: "PopUp d'information"
    type: file
    path: src/content/closure/closure-text.md
    fields:
      - name: closure
        label: Clôture
        type: object
        fields:
          - name: isVisible
            label: Afficher
            type: boolean
            default: false
          - name: title
            label: Titre
            type: string
            default: "Le site est en ligne !"
          - name: description
            label: Message
            type: text
            default: >
              Il reste encore quelques ingrédients à parsemer par-ci par-là, mais la base est là !
          - name: tag
            label: Formules de départ personnalisées
            type: string
            default: "Bon appétit !"

  - name: working-hours
    label: Horaires d'ouverture
    type: file
    path: src/content/workinghours/workinghours-text.md
    fields:
      - name: working_hours
        label: Jours de la semaine
        type: object
        fields:
          - name: lundi
            label: Lundi
            type: object
            fields:
              - { name: midi, label: Midi, type: string, default: "fermé" }
              - { name: soir, label: Soir, type: string, default: "fermé" }
          - name: mardi
            label: Mardi
            type: object
            fields:
              - {
                  name: midi,
                  label: Midi,
                  type: string,
                  default: "11:30-14:30",
                }
              - {
                  name: soir,
                  label: Soir,
                  type: string,
                  default: "18:30-21:00",
                }
          - name: mercredi
            label: Mercredi
            type: object
            fields:
              - {
                  name: midi,
                  label: Midi,
                  type: string,
                  default: "11:30-14:30",
                }
              - {
                  name: soir,
                  label: Soir,
                  type: string,
                  default: "18:30-21:00",
                }
          - name: jeudi
            label: Jeudi
            type: object
            fields:
              - {
                  name: midi,
                  label: Midi,
                  type: string,
                  default: "11:30-14:30",
                }
              - {
                  name: soir,
                  label: Soir,
                  type: string,
                  default: "18:30-21:00",
                }
          - name: vendredi
            label: Vendredi
            type: object
            fields:
              - {
                  name: midi,
                  label: Midi,
                  type: string,
                  default: "11:30-14:30",
                }
              - {
                  name: soir,
                  label: Soir,
                  type: string,
                  default: "18:30-21:00",
                }
          - name: samedi
            label: Samedi
            type: object
            fields:
              - {
                  name: midi,
                  label: Midi,
                  type: string,
                  default: "11:30-14:30",
                }
              - {
                  name: soir,
                  label: Soir,
                  type: string,
                  default: "18:30-21:00",
                }
          - name: dimanche
            label: Dimanche
            type: object
            fields:
              - {
                  name: midi,
                  label: Midi,
                  type: string,
                  default: "11:30-14:30",
                }
              - { name: soir, label: Soir, type: string, default: "fermé" }

  # Restaurant & Nearby Locations Specific Content
  - name: global
    label: Paragraphes des sections Restaurant et À proximité
    path: src/content/global
    type: collection
    fields:
      - name: heading
        label: "Titre"
        type: string
        default: "Titre"
      - name: subheading
        label: "Sous-Titre"
        type: string
        default: "Soustitre"
      - name: paragraph
        label: "Paragraphe"
        type: text
        default: "paragraphe"

  # Restaurant Specific Content
  - name: restaurant
    label: Restaurant
    type: collection
    path: src/content/restaurant
    fields:
      - name: id
        label: ID
        type: number
      - name: title
        label: Titre
        type: string
      - name: description
        label: Description
        type: string
      - name: image
        label: Images
        type: object
        fields:
          - name: src
            label: "Chemin vers le fichier de l'image"
            type: string
          - name: alt
            label: "Texte alternatif de l'image"
            type: string

  # Nearby Locations Content
  - name: nearby
    label: À proximité
    type: collection
    path: src/content/nearby
    fields:
      - name: id
        label: ID
        type: number
      - name: title
        label: Titre
        type: string
      - name: description
        label: Description
        type: string
      - name: image
        label: Images
        type: object
        fields:
          - name: src
            label: "Chemin vers le fichier de l'image"
            type: string
          - name: alt
            label: "Texte alternatif de l'image"
            type: string
      - name: url
        label: "lien vers la ressource"
        type: string

  - name: menus
    label: Liste des Cartes
    type: file
    path: src/content/menu/menu-text.md
    fields:
      - name: carte
        label: La Carte
        type: object
        fields:
          - name: title
            label: Titre
            type: string
            default: La carte
          - name: url
            label: URL
            type: string
            default: /docs/menus/cheznous_carte.pdf
      - name: vins
        label: Les Vins
        type: object
        fields:
          - name: title
            label: Titre
            type: string
            default: Les vins
          - name: url
            label: URL
            type: string
            default: /docs/menus/cheznous_carte_vins.pdf
      - name: special
        label: Menu Spécial
        type: object
        fields:
          - name: title
            label: Titre
            type: string
            default: "Menu spécial"
          - name: url
            label: URL
            type: string
            default: "/docs/menus/cheznous_menu_special.pdf"

  # Event Specific Content
  - name: event
    label: "Agenda"
    type: file
    path: src/content/event/event-text.md
    fields:
      - name: isVisible
        label: "Afficher l'évenement sur le site"
        type: boolean
        default: false
      - name: heading
        label: "Phrase d'accroche"
        type: string
        default: "A presto Chez Nous ! 🎉"
      - name: image
        label: "Image"
        type: object
        fields:
          - name: src
            label: "Chemin vers le fichier de l'image"
            type: string
            default: "./images/dummy-event.png"
          - name: alt
            label: "Texte alternatif de l'image"
            type: string
            default: "un événement de musique rock, avec un style graphique rétro."
      - name: title
        label: "Titre de l'événement"
        type: string
        default: "Soirée Pizza & Rock"
      - name: date
        label: "Date de l'événement (au format ISO)"
        type: date
        options:
          format: yyyy-MM-dd
        default: "2025-01-01"
      - name: time
        label: "Heure de début de l'événement (au format 24h)"
        type: string
        default: "19:00"
      - name: description
        label: "Description de l'événement"
        type: text
        default: >
          Partagez un moment convivial autour de nos meilleures pizzas, dans une ambiance rock et festive!
          Réservez votre table au 03 86 51 89 56.
      - name: link
        label: "Lien vers l'événement"
        type: string
        default: "https://example.com/"

  # Legal Content
  - name: mentions-legales
    label: Mentions Légales
    type: file
    path: src/content/legal/mentions-legales.md
    fields:
      - name: body
        label: Page mentions légales
        type: rich-text

  - name: politique-de-confidentialite
    label: Politique de Confidentialité
    type: file
    path: src/content/legal/politique-de-confidentialite.md
    fields:
      - name: body
        label: Page politique de confidentialité (RGPD)
        type: rich-text
